# Generated by Django 5.0.2 on 2026-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Product description in Arabic'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='Product description in French'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text='Product name in Arabic', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='Product name in French', max_length=200),
        ),
    ]
