# Generated by Django 5.0.2 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_ar_product_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_ar',
            field=models.CharField(blank=True, default='', help_text="Badge text in Arabic, e.g. 'جديد'", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_fr',
            field=models.CharField(blank=True, default='', help_text="Badge text in French, e.g. 'Nouveau'", max_length=50),
        ),
    ]
