# Generated by Django 5.0.2 on 2026-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français'), ('ar', 'العربية')], default='en', max_length=5),
        ),
    ]
