# Generated by Django 5.0.2 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Cart subtotal above which shipping is free.', max_digits=10)),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=5.99, help_text='Flat shipping cost when below the free threshold.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='HarvestTable', max_length=255)),
                ('contact_email', models.EmailField(default='hello@harvesttable.com', max_length=254)),
                ('currency', models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('MAD', 'MAD — Moroccan Dirham')], default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
