# Generated by Django 5.0.2 on 2026-03-10 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='standard_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.99'), help_text='Flat shipping cost when below the free threshold.', max_digits=10),
        ),
    ]
