# Generated by Django 5.0.2 on 2026-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_shippingsettings_standard_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=10),
        ),
    ]
